# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/green/OneDrive/Desktop/3D Mapping"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/green/OneDrive/Desktop/3D Mapping"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/green/OneDrive/Desktop/3D Mapping/CMakeFiles" "/mnt/c/Users/green/OneDrive/Desktop/3D Mapping//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/green/OneDrive/Desktop/3D Mapping/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OctreeProject

# Build rule for target.
OctreeProject: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OctreeProject
.PHONY : OctreeProject

# fast build rule for target.
OctreeProject/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/build
.PHONY : OctreeProject/fast

src/3d_model/PointCloud.o: src/3d_model/PointCloud.cpp.o
.PHONY : src/3d_model/PointCloud.o

# target to build an object file
src/3d_model/PointCloud.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/3d_model/PointCloud.cpp.o
.PHONY : src/3d_model/PointCloud.cpp.o

src/3d_model/PointCloud.i: src/3d_model/PointCloud.cpp.i
.PHONY : src/3d_model/PointCloud.i

# target to preprocess a source file
src/3d_model/PointCloud.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/3d_model/PointCloud.cpp.i
.PHONY : src/3d_model/PointCloud.cpp.i

src/3d_model/PointCloud.s: src/3d_model/PointCloud.cpp.s
.PHONY : src/3d_model/PointCloud.s

# target to generate assembly for a file
src/3d_model/PointCloud.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/3d_model/PointCloud.cpp.s
.PHONY : src/3d_model/PointCloud.cpp.s

src/3d_model/alpha_shapes.o: src/3d_model/alpha_shapes.cpp.o
.PHONY : src/3d_model/alpha_shapes.o

# target to build an object file
src/3d_model/alpha_shapes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/3d_model/alpha_shapes.cpp.o
.PHONY : src/3d_model/alpha_shapes.cpp.o

src/3d_model/alpha_shapes.i: src/3d_model/alpha_shapes.cpp.i
.PHONY : src/3d_model/alpha_shapes.i

# target to preprocess a source file
src/3d_model/alpha_shapes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/3d_model/alpha_shapes.cpp.i
.PHONY : src/3d_model/alpha_shapes.cpp.i

src/3d_model/alpha_shapes.s: src/3d_model/alpha_shapes.cpp.s
.PHONY : src/3d_model/alpha_shapes.s

# target to generate assembly for a file
src/3d_model/alpha_shapes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/3d_model/alpha_shapes.cpp.s
.PHONY : src/3d_model/alpha_shapes.cpp.s

src/FlightController/FlightController.o: src/FlightController/FlightController.cpp.o
.PHONY : src/FlightController/FlightController.o

# target to build an object file
src/FlightController/FlightController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/FlightController/FlightController.cpp.o
.PHONY : src/FlightController/FlightController.cpp.o

src/FlightController/FlightController.i: src/FlightController/FlightController.cpp.i
.PHONY : src/FlightController/FlightController.i

# target to preprocess a source file
src/FlightController/FlightController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/FlightController/FlightController.cpp.i
.PHONY : src/FlightController/FlightController.cpp.i

src/FlightController/FlightController.s: src/FlightController/FlightController.cpp.s
.PHONY : src/FlightController/FlightController.s

# target to generate assembly for a file
src/FlightController/FlightController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/FlightController/FlightController.cpp.s
.PHONY : src/FlightController/FlightController.cpp.s

src/drone_communication/Communicator.o: src/drone_communication/Communicator.cpp.o
.PHONY : src/drone_communication/Communicator.o

# target to build an object file
src/drone_communication/Communicator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/drone_communication/Communicator.cpp.o
.PHONY : src/drone_communication/Communicator.cpp.o

src/drone_communication/Communicator.i: src/drone_communication/Communicator.cpp.i
.PHONY : src/drone_communication/Communicator.i

# target to preprocess a source file
src/drone_communication/Communicator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/drone_communication/Communicator.cpp.i
.PHONY : src/drone_communication/Communicator.cpp.i

src/drone_communication/Communicator.s: src/drone_communication/Communicator.cpp.s
.PHONY : src/drone_communication/Communicator.s

# target to generate assembly for a file
src/drone_communication/Communicator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/drone_communication/Communicator.cpp.s
.PHONY : src/drone_communication/Communicator.cpp.s

src/enviroment/enviroment.o: src/enviroment/enviroment.cpp.o
.PHONY : src/enviroment/enviroment.o

# target to build an object file
src/enviroment/enviroment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/enviroment/enviroment.cpp.o
.PHONY : src/enviroment/enviroment.cpp.o

src/enviroment/enviroment.i: src/enviroment/enviroment.cpp.i
.PHONY : src/enviroment/enviroment.i

# target to preprocess a source file
src/enviroment/enviroment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/enviroment/enviroment.cpp.i
.PHONY : src/enviroment/enviroment.cpp.i

src/enviroment/enviroment.s: src/enviroment/enviroment.cpp.s
.PHONY : src/enviroment/enviroment.s

# target to generate assembly for a file
src/enviroment/enviroment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/enviroment/enviroment.cpp.s
.PHONY : src/enviroment/enviroment.cpp.s

src/enviroment/octree/Octree.o: src/enviroment/octree/Octree.cpp.o
.PHONY : src/enviroment/octree/Octree.o

# target to build an object file
src/enviroment/octree/Octree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/enviroment/octree/Octree.cpp.o
.PHONY : src/enviroment/octree/Octree.cpp.o

src/enviroment/octree/Octree.i: src/enviroment/octree/Octree.cpp.i
.PHONY : src/enviroment/octree/Octree.i

# target to preprocess a source file
src/enviroment/octree/Octree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/enviroment/octree/Octree.cpp.i
.PHONY : src/enviroment/octree/Octree.cpp.i

src/enviroment/octree/Octree.s: src/enviroment/octree/Octree.cpp.s
.PHONY : src/enviroment/octree/Octree.s

# target to generate assembly for a file
src/enviroment/octree/Octree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/enviroment/octree/Octree.cpp.s
.PHONY : src/enviroment/octree/Octree.cpp.s

src/enviroment/pathfinding/a_star.o: src/enviroment/pathfinding/a_star.cpp.o
.PHONY : src/enviroment/pathfinding/a_star.o

# target to build an object file
src/enviroment/pathfinding/a_star.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/enviroment/pathfinding/a_star.cpp.o
.PHONY : src/enviroment/pathfinding/a_star.cpp.o

src/enviroment/pathfinding/a_star.i: src/enviroment/pathfinding/a_star.cpp.i
.PHONY : src/enviroment/pathfinding/a_star.i

# target to preprocess a source file
src/enviroment/pathfinding/a_star.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/enviroment/pathfinding/a_star.cpp.i
.PHONY : src/enviroment/pathfinding/a_star.cpp.i

src/enviroment/pathfinding/a_star.s: src/enviroment/pathfinding/a_star.cpp.s
.PHONY : src/enviroment/pathfinding/a_star.s

# target to generate assembly for a file
src/enviroment/pathfinding/a_star.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/enviroment/pathfinding/a_star.cpp.s
.PHONY : src/enviroment/pathfinding/a_star.cpp.s

src/enviroment/pathfinding/bresenham_3d.o: src/enviroment/pathfinding/bresenham_3d.cpp.o
.PHONY : src/enviroment/pathfinding/bresenham_3d.o

# target to build an object file
src/enviroment/pathfinding/bresenham_3d.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/enviroment/pathfinding/bresenham_3d.cpp.o
.PHONY : src/enviroment/pathfinding/bresenham_3d.cpp.o

src/enviroment/pathfinding/bresenham_3d.i: src/enviroment/pathfinding/bresenham_3d.cpp.i
.PHONY : src/enviroment/pathfinding/bresenham_3d.i

# target to preprocess a source file
src/enviroment/pathfinding/bresenham_3d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/enviroment/pathfinding/bresenham_3d.cpp.i
.PHONY : src/enviroment/pathfinding/bresenham_3d.cpp.i

src/enviroment/pathfinding/bresenham_3d.s: src/enviroment/pathfinding/bresenham_3d.cpp.s
.PHONY : src/enviroment/pathfinding/bresenham_3d.s

# target to generate assembly for a file
src/enviroment/pathfinding/bresenham_3d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/enviroment/pathfinding/bresenham_3d.cpp.s
.PHONY : src/enviroment/pathfinding/bresenham_3d.cpp.s

src/enviroment/pathfinding/locate_targets.o: src/enviroment/pathfinding/locate_targets.cpp.o
.PHONY : src/enviroment/pathfinding/locate_targets.o

# target to build an object file
src/enviroment/pathfinding/locate_targets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/enviroment/pathfinding/locate_targets.cpp.o
.PHONY : src/enviroment/pathfinding/locate_targets.cpp.o

src/enviroment/pathfinding/locate_targets.i: src/enviroment/pathfinding/locate_targets.cpp.i
.PHONY : src/enviroment/pathfinding/locate_targets.i

# target to preprocess a source file
src/enviroment/pathfinding/locate_targets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/enviroment/pathfinding/locate_targets.cpp.i
.PHONY : src/enviroment/pathfinding/locate_targets.cpp.i

src/enviroment/pathfinding/locate_targets.s: src/enviroment/pathfinding/locate_targets.cpp.s
.PHONY : src/enviroment/pathfinding/locate_targets.s

# target to generate assembly for a file
src/enviroment/pathfinding/locate_targets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/enviroment/pathfinding/locate_targets.cpp.s
.PHONY : src/enviroment/pathfinding/locate_targets.cpp.s

src/enviroment/point/point.o: src/enviroment/point/point.cpp.o
.PHONY : src/enviroment/point/point.o

# target to build an object file
src/enviroment/point/point.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/enviroment/point/point.cpp.o
.PHONY : src/enviroment/point/point.cpp.o

src/enviroment/point/point.i: src/enviroment/point/point.cpp.i
.PHONY : src/enviroment/point/point.i

# target to preprocess a source file
src/enviroment/point/point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/enviroment/point/point.cpp.i
.PHONY : src/enviroment/point/point.cpp.i

src/enviroment/point/point.s: src/enviroment/point/point.cpp.s
.PHONY : src/enviroment/point/point.s

# target to generate assembly for a file
src/enviroment/point/point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/enviroment/point/point.cpp.s
.PHONY : src/enviroment/point/point.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/OctreeProject.dir/build.make CMakeFiles/OctreeProject.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... OctreeProject"
	@echo "... src/3d_model/PointCloud.o"
	@echo "... src/3d_model/PointCloud.i"
	@echo "... src/3d_model/PointCloud.s"
	@echo "... src/3d_model/alpha_shapes.o"
	@echo "... src/3d_model/alpha_shapes.i"
	@echo "... src/3d_model/alpha_shapes.s"
	@echo "... src/FlightController/FlightController.o"
	@echo "... src/FlightController/FlightController.i"
	@echo "... src/FlightController/FlightController.s"
	@echo "... src/drone_communication/Communicator.o"
	@echo "... src/drone_communication/Communicator.i"
	@echo "... src/drone_communication/Communicator.s"
	@echo "... src/enviroment/enviroment.o"
	@echo "... src/enviroment/enviroment.i"
	@echo "... src/enviroment/enviroment.s"
	@echo "... src/enviroment/octree/Octree.o"
	@echo "... src/enviroment/octree/Octree.i"
	@echo "... src/enviroment/octree/Octree.s"
	@echo "... src/enviroment/pathfinding/a_star.o"
	@echo "... src/enviroment/pathfinding/a_star.i"
	@echo "... src/enviroment/pathfinding/a_star.s"
	@echo "... src/enviroment/pathfinding/bresenham_3d.o"
	@echo "... src/enviroment/pathfinding/bresenham_3d.i"
	@echo "... src/enviroment/pathfinding/bresenham_3d.s"
	@echo "... src/enviroment/pathfinding/locate_targets.o"
	@echo "... src/enviroment/pathfinding/locate_targets.i"
	@echo "... src/enviroment/pathfinding/locate_targets.s"
	@echo "... src/enviroment/point/point.o"
	@echo "... src/enviroment/point/point.i"
	@echo "... src/enviroment/point/point.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

